Shex reports

diff --git a/shex b/shex
--- a/shex
+++ b/shex
@@ -1,64 +1,69 @@
 #!/bin/bash
 
-REPO=/home/afs/.m2/repo
-JVER=4.2.0-SNAPSHOT
-
-read -r -d '' DEV << EOM
-$REPO/org/apache/jena/apache-jena-libs/$JVER/apache-jena-libs-$JVER.pom
-$REPO/org/apache/jena/jena-shacl/$JVER/jena-shacl-$JVER.jar
-$REPO/org/apache/jena/jena-arq/$JVER/jena-arq-$JVER.jar
-$REPO/org/apache/jena/jena-tdb/$JVER/jena-tdb-$JVER.jar
-$REPO/org/apache/jena/jena-tdb2/$JVER/jena-tdb2-$JVER.jar
-$REPO/org/apache/jena/jena-dboe-storage/$JVER/jena-dboe-storage-$JVER.jar
-$REPO/org/apache/jena/jena-dboe-trans-data/$JVER/jena-dboe-trans-data-$JVER.jar
-$REPO/org/apache/jena/jena-dboe-transaction/$JVER/jena-dboe-transaction-$JVER.jar
-$REPO/org/apache/jena/jena-dboe-base/$JVER/jena-dboe-base-$JVER.jar
-$REPO/org/apache/jena/jena-dboe-index/$JVER/jena-dboe-index-$JVER.jar
-$REPO/org/apache/jena/jena-rdfconnection/$JVER/jena-rdfconnection-$JVER.jar
-$REPO/org/apache/jena/jena-base/$JVER/jena-base-$JVER-tests.jar
-$REPO/org/apache/jena/jena-core/$JVER/jena-core-$JVER-tests.jar
-$REPO/org/apache/jena/jena-base/$JVER/jena-base-$JVER.jar
-$REPO/org/apache/jena/jena-iri/$JVER/jena-iri-$JVER.jar
-$REPO/org/apache/jena/jena-cmds/$JVER/jena-cmds-$JVER.jar
-$REPO/org/apache/jena/jena-cmds/$JVER/jena-cmds-$JVER-tests.jar
-$REPO/org/apache/jena/jena-arq/$JVER/jena-arq-$JVER-tests.jar
-$REPO/org/apache/jena/jena-core/$JVER/jena-core-$JVER.jar
-$REPO/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
-$REPO/org/apache/jena/jena-shaded-guava/$JVER/jena-shaded-guava-$JVER.jar
-$REPO/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar
-$REPO/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar
-$REPO/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
-$REPO/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
-$REPO/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar
-$REPO/com/github/andrewoma/dexx/collection/0.7/collection-0.7.jar
-$REPO/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
-$REPO/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
-$REPO/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar
-$REPO/com/github/jsonld-java/jsonld-java/0.13.3/jsonld-java-0.13.3.jar
-$REPO/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar
-$REPO/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar
-$REPO/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar
-$REPO/org/apache/httpcomponents/httpclient-cache/4.5.13/httpclient-cache-4.5.13.jar
-$REPO/org/apache/thrift/libthrift/0.14.1/libthrift-0.14.1.jar
-$REPO/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar
-$REPO/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar
-$REPO/junit/junit/4.13.1/junit-4.13.1.jar
-$REPO/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
-$REPO/org/apache/logging/log4j/log4j-slf4j-impl/2.13.3/log4j-slf4j-impl-2.13.3.jar
-$REPO/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar
-$REPO/org/apache/logging/log4j/log4j-core/2.13.3/log4j-core-2.13.3.jar
-EOM
-
-for D in $DEV
-do
-    if [ -e "$D" ]
-    then
-	CP="$D:$CP"
-    else
-	echo "Not found: $D" 1>&2
-    fi
-done
-
+CP="$(jena CP)"
 CP="$HOME/ASF/shapes/jena-shex/target/classes:$CP"
 #echo $CP
-java -cp "$CP" cmd.shex "$@"
+exec java -cp "$CP" cmd.shex "$@"
+h
+
+## REPO=/home/afs/.m2/repo
+## JVER=4.2.0-SNAPSHOT
+## read -r -d '' DEV << EOM
+## $REPO/org/apache/jena/apache-jena-libs/$JVER/apache-jena-libs-$JVER.pom
+## $REPO/org/apache/jena/jena-shacl/$JVER/jena-shacl-$JVER.jar
+## $REPO/org/apache/jena/jena-arq/$JVER/jena-arq-$JVER.jar
+## $REPO/org/apache/jena/jena-tdb/$JVER/jena-tdb-$JVER.jar
+## $REPO/org/apache/jena/jena-tdb2/$JVER/jena-tdb2-$JVER.jar
+## $REPO/org/apache/jena/jena-dboe-storage/$JVER/jena-dboe-storage-$JVER.jar
+## $REPO/org/apache/jena/jena-dboe-trans-data/$JVER/jena-dboe-trans-data-$JVER.jar
+## $REPO/org/apache/jena/jena-dboe-transaction/$JVER/jena-dboe-transaction-$JVER.jar
+## $REPO/org/apache/jena/jena-dboe-base/$JVER/jena-dboe-base-$JVER.jar
+## $REPO/org/apache/jena/jena-dboe-index/$JVER/jena-dboe-index-$JVER.jar
+## $REPO/org/apache/jena/jena-rdfconnection/$JVER/jena-rdfconnection-$JVER.jar
+## $REPO/org/apache/jena/jena-base/$JVER/jena-base-$JVER-tests.jar
+## $REPO/org/apache/jena/jena-core/$JVER/jena-core-$JVER-tests.jar
+## $REPO/org/apache/jena/jena-base/$JVER/jena-base-$JVER.jar
+## $REPO/org/apache/jena/jena-iri/$JVER/jena-iri-$JVER.jar
+## $REPO/org/apache/jena/jena-cmds/$JVER/jena-cmds-$JVER.jar
+## $REPO/org/apache/jena/jena-cmds/$JVER/jena-cmds-$JVER-tests.jar
+## $REPO/org/apache/jena/jena-arq/$JVER/jena-arq-$JVER-tests.jar
+## $REPO/org/apache/jena/jena-core/$JVER/jena-core-$JVER.jar
+## $REPO/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
+## $REPO/org/apache/jena/jena-shaded-guava/$JVER/jena-shaded-guava-$JVER.jar
+## $REPO/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar
+## $REPO/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar
+## $REPO/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
+## $REPO/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
+## $REPO/org/apache/commons/commons-compress/1.20/commons-compress-1.20.jar
+## $REPO/com/github/andrewoma/dexx/collection/0.7/collection-0.7.jar
+## $REPO/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
+## $REPO/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
+## $REPO/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.jar
+## $REPO/com/github/jsonld-java/jsonld-java/0.13.3/jsonld-java-0.13.3.jar
+## $REPO/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar
+## $REPO/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar
+## $REPO/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar
+## $REPO/org/apache/httpcomponents/httpclient-cache/4.5.13/httpclient-cache-4.5.13.jar
+## $REPO/org/apache/thrift/libthrift/0.14.1/libthrift-0.14.1.jar
+## $REPO/javax/annotation/javax.annotation-api/1.3.2/javax.annotation-api-1.3.2.jar
+## $REPO/org/slf4j/jcl-over-slf4j/1.7.30/jcl-over-slf4j-1.7.30.jar
+## $REPO/junit/junit/4.13.1/junit-4.13.1.jar
+## $REPO/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
+## $REPO/org/apache/logging/log4j/log4j-slf4j-impl/2.13.3/log4j-slf4j-impl-2.13.3.jar
+## $REPO/org/apache/logging/log4j/log4j-api/2.13.3/log4j-api-2.13.3.jar
+## $REPO/org/apache/logging/log4j/log4j-core/2.13.3/log4j-core-2.13.3.jar
+## EOM
+## 
+## for D in $DEV
+## do
+##     if [ -e "$D" ]
+##     then
+## 	CP="$D:$CP"
+##     else
+## 	echo "Not found: $D" 1>&2
+##     fi
+## done
+
+## CP="$HOME/ASF/shapes/jena-shex/target/classes:$CP"
+## #echo $CP
+## java -cp "$CP" cmd.shex "$@"
